server:
  port: 8000

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 426430630258-11fkoupg8centkivmi6jpp8d98rs2tls.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB



mybatis:
  mapper-locations:
    - /mappers/*.xml

file:
  path: C:/junil/younggyu/Library-springboot-202301-younggyu/upload/
